apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-flask
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: flask
        phase: test
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - name: http-port
              containerPort: 80


